_BASE_: ../segmentation_base.yaml

OUTPUT_DIR: ./output/region

NAME: brievenboeken

PREPROCESS:
  REGION:
    REGIONS:
      [
        "tekstblok",
        "ondertekening",
        "zijkopmetadata",
        "Aanhef",
        "paginanummer",
        "marginalia",
        "titel",
        "misc",
        "lijst",
        "zijkopbijlage",
        "zijkop",
        "page-number",
        "afschrift",
      ]
    MERGE_REGIONS: []
    REGION_TYPE: []

  RESIZE:
    RESIZE_MODE: "scaling"
    SCALING: 0.33

INPUT:
  FORMAT: RGB

  RESIZE_MODE: "scaling"
  SCALING_TRAIN: 1.0
  MAX_SIZE_TRAIN: -1

  CROP:
    ENABLED: true
    SIZE: [2048, 2048]
    TYPE: absolute

  MAX_SIZE_TEST: -1

  GRAYSCALE:
    PROBABILITY: 0.1

  ADAPTIVE_THRESHOLDING:
    PROBABILITY: 0.05

  BRIGHTNESS:
    PROBABILITY: 0.25
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  CONTRAST:
    PROBABILITY: 0.25
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  SATURATION:
    PROBABILITY: 0.25
    MIN_INTENSITY: 0.5
    MAX_INTENSITY: 1.5

  HUE:
    PROBABILITY: 0.25
    MIN_DELTA: -0.25
    MAX_DELTA: 0.25

  INVERT:
    PROBABILITY: 0.1

  JPEG_COMPRESSION:
    PROBABILITY: 0.25
    MIN_QUALITY: 50
    MAX_QUALITY: 100

  NOISE:
    PROBABILITY: 0.25
    MIN_STD: 10
    MAX_STD: 32

  GAUSSIAN_FILTER:
    PROBABILITY: 0.25
    MIN_SIGMA: 0.5
    MAX_SIGMA: 1.5

  HORIZONTAL_FLIP:
    PROBABILITY: 0.

  VERTICAL_FLIP:
    PROBABILITY: 0.

  ELASTIC_DEFORMATION:
    PROBABILITY: 0.25
    ALPHA: 0.1
    SIGMA: 0.01

  AFFINE:
    PROBABILITY: 1.

    TRANSLATION:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.02

    ROTATION:
      PROBABILITY: 0.9
      KAPPA: 30.

    SHEAR:
      PROBABILITY: 0.9
      KAPPA: 20.

    SCALE:
      PROBABILITY: 0.9
      STANDARD_DEVIATION: 0.12

  ORIENTATION:
    PROBABILITY: 1.0
    PERCENTAGES: (0.25, 0.25, 0.25, 0.25)

MODEL:
  MODE: region

  SEM_SEG_HEAD:
    NUM_CLASSES: 14

  WEIGHTS:

TRAIN:
  WEIGHTS:

TEST:
  WEIGHTS:
  EVAL_PERIOD: 10000

SOLVER:
  MAX_ITER: 250000
  CHECKPOINT_PERIOD: 25000
  AMP:
    ENABLED: true
  IMS_PER_BATCH: 4
